from nicegui import ui, app
from theme import init_colors
from api import APIClient
from dbus_next.aio import MessageBus
from dbus_next import BusType
from network_manager import  nm

"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager
Bus name   : org.freedesktop.NetworkManager
"""

from jeepney.wrappers import MessageGenerator, new_method_call
from jeepney.io.asyncio import open_dbus_router, Proxy

class NetworkManager(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager'

    def __init__(self, object_path='/org/freedesktop/NetworkManager',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)

    def Reload(self, flags):
        return new_method_call(self, 'Reload', 'u',
                               (flags,))

    def GetDevices(self):
        return new_method_call(self, 'GetDevices')

    def GetAllDevices(self):
        return new_method_call(self, 'GetAllDevices')

    def GetDeviceByIpIface(self, iface):
        return new_method_call(self, 'GetDeviceByIpIface', 's',
                               (iface,))

    def ActivateConnection(self, connection, device, specific_object):
        return new_method_call(self, 'ActivateConnection', 'ooo',
                               (connection, device, specific_object))

    def AddAndActivateConnection(self, connection, device, specific_object):
        return new_method_call(self, 'AddAndActivateConnection', 'a{sa{sv}}oo',
                               (connection, device, specific_object))

    def AddAndActivateConnection2(self, connection, device, specific_object, options):
        return new_method_call(self, 'AddAndActivateConnection2', 'a{sa{sv}}ooa{sv}',
                               (connection, device, specific_object, options))

    def DeactivateConnection(self, active_connection):
        return new_method_call(self, 'DeactivateConnection', 'o',
                               (active_connection,))

    def Sleep(self, sleep):
        return new_method_call(self, 'Sleep', 'b',
                               (sleep,))

    def Enable(self, enable):
        return new_method_call(self, 'Enable', 'b',
                               (enable,))

    def GetPermissions(self):
        return new_method_call(self, 'GetPermissions')

    def SetLogging(self, level, domains):
        return new_method_call(self, 'SetLogging', 'ss',
                               (level, domains))

    def GetLogging(self):
        return new_method_call(self, 'GetLogging')

    def CheckConnectivity(self):
        return new_method_call(self, 'CheckConnectivity')

    def state(self):
        return new_method_call(self, 'state')

    def CheckpointCreate(self, devices, rollback_timeout, flags):
        return new_method_call(self, 'CheckpointCreate', 'aouu',
                               (devices, rollback_timeout, flags))

    def CheckpointDestroy(self, checkpoint):
        return new_method_call(self, 'CheckpointDestroy', 'o',
                               (checkpoint,))

    def CheckpointRollback(self, checkpoint):
        return new_method_call(self, 'CheckpointRollback', 'o',
                               (checkpoint,))

    def CheckpointAdjustRollbackTimeout(self, checkpoint, add_timeout):
        return new_method_call(self, 'CheckpointAdjustRollbackTimeout', 'ou',
                               (checkpoint, add_timeout))



def update_dhcp_mode(dhcp_value):  # Receives the selected value
    print(f"Selected DHCP mode: {dhcp_value}")


def format_interfaces(result):
    table_rows = []
    for iface in result["interfaces"]:
        addresses_str = (
            ", ".join(iface.get("addresses", [])) if iface.get("addresses") else "None"
        )
        table_rows.append({"name": iface["name"], "addresses": addresses_str})
    return table_rows


async def get_interfaces_and_addresses() -> list:


    #devices = await nm.nm_property("Devices")

    devices = await nm.nm_method("get_devices")

    for d in devices:
        res= await nm.device_property(d, "Autoconnect")
        print(res)
        if await nm.device_property(d, "Autoconnect"):
            print(d)
        #res = await nm.device_method(d, "call_get_applied_connection", 0)
        #print(d)
    #    f = await nm.device(d, "call_get_applied_connection", 0)
    #    print(f)
#
    #    print(await nm.device_property(d, "Interface"))

    table_rows = []
    '''
    nm.introspection = await nm.bus.introspect('org.freedesktop.NetworkManager', '/org/freedesktop/NetworkManager')
    nm.object = nm.bus.get_proxy_object('org.freedesktop.NetworkManager', '/org/freedesktop/NetworkManager', nm.introspection)
    nm.interface = nm.object.get_interface('org.freedesktop.NetworkManager')
    nm.properties_interface = nm.object.get_interface('org.freedesktop.DBus.Properties')

    dp = await nm.interface.call_get_devices()



    for path in dp:
        address_data = []

        nm.introspection = await nm.bus.introspect('org.freedesktop.NetworkManager', path)
        nm.object = nm.bus.get_proxy_object('org.freedesktop.NetworkManager', path, nm.introspection)
        nm.interface = nm.object.get_interface('org.freedesktop.NetworkManager.Device')
        nm.properties_interface = nm.object.get_interface('org.freedesktop.DBus.Properties')


        interface_name = await nm.properties_interface.call_get(
        "org.freedesktop.NetworkManager.Device",  # Interface name
        "Interface"                               # Property name
        )


        ipv4_conf = await nm.properties_interface.call_get(        
            "org.freedesktop.NetworkManager.Device",   
            "Ip4Config")    
        
        ipv6_conf = await nm.properties_interface.call_get(        
            "org.freedesktop.NetworkManager.Device",   
            "Ip6Config")   

        nm.introspection = await nm.bus.introspect('org.freedesktop.NetworkManager', ipv4_conf.value)
        nm.object = nm.bus.get_proxy_object('org.freedesktop.NetworkManager', ipv4_conf.value, nm.introspection)
        nm.interface = nm.object.get_interface('org.freedesktop.NetworkManager.IP4Config')
        nm.properties_interface = nm.object.get_interface('org.freedesktop.DBus.Properties')

        ip4_address_data = await nm.properties_interface.call_get(        
            "org.freedesktop.NetworkManager.IP4Config",   
            "AddressData")    
        

        address_data.extend(ip4_address_data.value)




        nm.introspection = await nm.bus.introspect('org.freedesktop.NetworkManager', ipv6_conf.value)
        nm.object = nm.bus.get_proxy_object('org.freedesktop.NetworkManager', ipv6_conf.value, nm.introspection)
        nm.interface = nm.object.get_interface('org.freedesktop.NetworkManager.IP6Config')
        nm.properties_interface = nm.object.get_interface('org.freedesktop.DBus.Properties')

        ip6_address_data = await nm.properties_interface.call_get(        
            "org.freedesktop.NetworkManager.IP6Config",   
            "AddressData")    
        
        address_data.extend(ip6_address_data.value)
        
        address_string = ", ".join(
            f"{item['address'].value}/{item['prefix'].value}" 
            for item in address_data
        )

        table_rows.append({"name": interface_name.value, "addresses": address_string})





        nm.introspection = await nm.bus.introspect('org.freedesktop.NetworkManager', path)
        nm.object = nm.bus.get_proxy_object('org.freedesktop.NetworkManager', path, nm.introspection)
        nm.interface = nm.object.get_interface('org.freedesktop.NetworkManager.Device')
        nm.properties_interface = nm.object.get_interface('org.freedesktop.DBus.Properties')


        bytes = await nm.properties_interface.call_get(        
                "org.freedesktop.NetworkManager.Device.Statistics",   
                "TxBytes")  
        print("bytes", bytes.value)

    '''


    return table_rows





async def on_row_selected(event):
    row = event.args[1] if event.args[1] else None
    if row:
        with ui.dialog() as interface_dialog, ui.card():
            ui.label(f"Interface Details: {row['name']}").classes("text-h6 mb-4")
            await interface_card(row["name"])
            ui.button("Close", on_click=interface_dialog.close).classes("bg-secondary")

        interface_dialog.open()
        

async def network_page():



    with ui.column():
        interfaces = await get_interfaces_and_addresses()

        #res = await nm.getNetworkManger()
        #print(res)
        ui.label("Networking").classes("text-h5")

        interface_table = ui.table(
            title="Interfaces",
            #rows=interfaces,
            rows=[{'d':'v'}],
            column_defaults={
                "align": "left",
                "headerClasses": "uppercase text-primary",
            },
        )


        interface_table.add_slot('body-cell-name', '''
            <q-td :props="props">
                <a :href="'/networking/' + props.row.name" 
                   class="text-accent cursor-pointer hover:underline"
                   >
                    {{ props.value }}
                </a>
            </q-td>
        ''')


async def interface_page(interface_name: str):

    with ui.row():
        ui.link('Networking', '/networking')
        ui.label('>')
        ui.label(interface_name)



        await interface_card(interface_name)



async def interface_card(iface :str ):

    '''

    nm.introspection = await nm.bus.introspect('org.freedesktop.NetworkManager', "/org/freedesktop/NetworkManager")
    nm.object = nm.bus.get_proxy_object('org.freedesktop.NetworkManager', "/org/freedesktop/NetworkManager", nm.introspection)
    nm.interface = nm.object.get_interface('org.freedesktop.NetworkManager')
    device = await nm.interface.call_get_device_by_ip_iface(iface)





    nm.introspection = await nm.bus.introspect('org.freedesktop.NetworkManager', device)
    nm.object = nm.bus.get_proxy_object('org.freedesktop.NetworkManager', device, nm.introspection)
    #nm.interface = nm.object.get_interface('org.freedesktop.NetworkManager.Device')
    nm.properties_interface = nm.object.get_interface('org.freedesktop.DBus.Properties')


    hwaddr = await nm.properties_interface.call_get(        
            "org.freedesktop.NetworkManager.Device.Wired",   
            "HwAddress")  


    hwaddr = await nm.properties_interface.call_get(        
            "org.freedesktop.NetworkManager.Device.Wired",   
            "HwAddress")  
    
    carrier = await nm.properties_interface.call_get(        
            "org.freedesktop.NetworkManager.Device.Wired",   
            "Carrier")  
    print((carrier.value))
    speed = await nm.properties_interface.call_get(        
            "org.freedesktop.NetworkManager.Device.Wired",   
            "Speed")  
   
    print(speed)
    driver = await nm.properties_interface.call_get(        
            "org.freedesktop.NetworkManager.Device",   
            "Driver")  
    

    id = await nm.properties_interface.call_get(        
            "org.freedesktop.NetworkManager.Device",   
            "PhysicalPortId")  

    print(driver.value)

    print(id.value)


    


    address_data = []
    ipv4_conf = await nm.properties_interface.call_get(        
        "org.freedesktop.NetworkManager.Device",   
        "Ip4Config")    
    
    ipv6_conf = await nm.properties_interface.call_get(        
        "org.freedesktop.NetworkManager.Device",   
        "Ip6Config")   
    nm.introspection = await nm.bus.introspect('org.freedesktop.NetworkManager', ipv4_conf.value)
    nm.object = nm.bus.get_proxy_object('org.freedesktop.NetworkManager', ipv4_conf.value, nm.introspection)
    nm.interface = nm.object.get_interface('org.freedesktop.NetworkManager.IP4Config')
    nm.properties_interface = nm.object.get_interface('org.freedesktop.DBus.Properties')
    ip4_address_data = await nm.properties_interface.call_get(        
        "org.freedesktop.NetworkManager.IP4Config",   
        "AddressData")    
    
    address_data.extend(ip4_address_data.value)
    nm.introspection = await nm.bus.introspect('org.freedesktop.NetworkManager', ipv6_conf.value)
    nm.object = nm.bus.get_proxy_object('org.freedesktop.NetworkManager', ipv6_conf.value, nm.introspection)
    nm.interface = nm.object.get_interface('org.freedesktop.NetworkManager.IP6Config')
    nm.properties_interface = nm.object.get_interface('org.freedesktop.DBus.Properties')
    ip6_address_data = await nm.properties_interface.call_get(        
        "org.freedesktop.NetworkManager.IP6Config",   
        "AddressData")    
    
    address_data.extend(ip6_address_data.value)
    
    address_string = ", ".join(
        f"{item['address'].value}/{item['prefix'].value}" 
        for item in address_data
    )

    


    with ui.card().classes("w-full"):
        # Header row
        with ui.row().classes("w-full items-center justify-between"):
            ui.label(iface).classes("text-h6")
            ui.label(f"{driver.value}").classes("text-h6")
            ui.label(f"{hwaddr.value}").classes("text-h6")
            ui.switch("Connected").props("disable")

        ui.separator()
        


        with ui.row().classes("w-full gap-4"):
            with ui.column().classes("w-32 items-start"):  # Fixed width for labels
               ui.label("Status").classes("font-bold")
               ui.label("Carrier").classes("font-bold")
               ui.label("General").classes("font-bold")
               ui.label("IPv4").classes("font-bold")
               ui.label("IPv6").classes("font-bold")
               ui.label("MTU").classes("font-bold")
    
            with ui.column().classes("flex-1 gap-4"):  # Flexible width for values
                ui.label(address_string)

                ui.label(f"{speed.value/1000} Gbps")
               
                ui.checkbox('Connect automatically').props("flat color=accent align=left").classes("w-full").props("dense")

                with ui.row():
                    ui.label(address_string), ui.link("edit")

                with ui.row():
                    ui.label(address_string), ui.link("edit")
                
                with ui.row():
                    ui.label(address_string), ui.link("edit")
         '''