"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager
Bus name   : org.freedesktop.NetworkManager
"""

from jeepney.wrappers import MessageGenerator, new_method_call


class NetworkManager(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager'

    def __init__(self, object_path='/org/freedesktop/NetworkManager',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)

    def Reload(self, flags):
        return new_method_call(self, 'Reload', 'u',
                               (flags,))

    def GetDevices(self):
        return new_method_call(self, 'GetDevices')

    def GetAllDevices(self):
        return new_method_call(self, 'GetAllDevices')

    def GetDeviceByIpIface(self, iface):
        return new_method_call(self, 'GetDeviceByIpIface', 's',
                               (iface,))

    def ActivateConnection(self, connection, device, specific_object):
        return new_method_call(self, 'ActivateConnection', 'ooo',
                               (connection, device, specific_object))

    def AddAndActivateConnection(self, connection, device, specific_object):
        return new_method_call(self, 'AddAndActivateConnection', 'a{sa{sv}}oo',
                               (connection, device, specific_object))

    def AddAndActivateConnection2(self, connection, device, specific_object, options):
        return new_method_call(self, 'AddAndActivateConnection2', 'a{sa{sv}}ooa{sv}',
                               (connection, device, specific_object, options))

    def DeactivateConnection(self, active_connection):
        return new_method_call(self, 'DeactivateConnection', 'o',
                               (active_connection,))

    def Sleep(self, sleep):
        return new_method_call(self, 'Sleep', 'b',
                               (sleep,))

    def Enable(self, enable):
        return new_method_call(self, 'Enable', 'b',
                               (enable,))

    def GetPermissions(self):
        return new_method_call(self, 'GetPermissions')

    def SetLogging(self, level, domains):
        return new_method_call(self, 'SetLogging', 'ss',
                               (level, domains))

    def GetLogging(self):
        return new_method_call(self, 'GetLogging')

    def CheckConnectivity(self):
        return new_method_call(self, 'CheckConnectivity')

    def state(self):
        return new_method_call(self, 'state')

    def CheckpointCreate(self, devices, rollback_timeout, flags):
        return new_method_call(self, 'CheckpointCreate', 'aouu',
                               (devices, rollback_timeout, flags))

    def CheckpointDestroy(self, checkpoint):
        return new_method_call(self, 'CheckpointDestroy', 'o',
                               (checkpoint,))

    def CheckpointRollback(self, checkpoint):
        return new_method_call(self, 'CheckpointRollback', 'o',
                               (checkpoint,))

    def CheckpointAdjustRollbackTimeout(self, checkpoint, add_timeout):
        return new_method_call(self, 'CheckpointAdjustRollbackTimeout', 'ou',
                               (checkpoint, add_timeout))
