"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager/Settings/1
Bus name   : org.freedesktop.NetworkManager
"""

from jeepney.wrappers import MessageGenerator, new_method_call


class Connection(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Settings.Connection'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/Settings/1',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)

    def Update(self, properties):
        return new_method_call(self, 'Update', 'a{sa{sv}}',
                               (properties,))

    def UpdateUnsaved(self, properties):
        return new_method_call(self, 'UpdateUnsaved', 'a{sa{sv}}',
                               (properties,))

    def Delete(self):
        return new_method_call(self, 'Delete')

    def GetSettings(self):
        return new_method_call(self, 'GetSettings')

    def GetSecrets(self, setting_name):
        return new_method_call(self, 'GetSecrets', 's',
                               (setting_name,))

    def ClearSecrets(self):
        return new_method_call(self, 'ClearSecrets')

    def Save(self):
        return new_method_call(self, 'Save')

    def Update2(self, settings, flags, args):
        return new_method_call(self, 'Update2', 'a{sa{sv}}ua{sv}',
                               (settings, flags, args))
