"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager/Devices/2
Bus name   : org.freedesktop.NetworkManager
"""

import asyncio
from dataclasses import dataclass, fields
from typing import Any, Optional, Self
from jeepney.wrappers import MessageGenerator, new_method_call
from jeepney.io.asyncio import open_dbus_router, Proxy, DBusRouter, DBusConnection, open_dbus_connection

class Statistics(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Device.Statistics'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/Devices/2',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)


@dataclass
class DeviceProperties:
    Udi                   : Optional [str] = None        #    s
    Path                  : Optional [str] = None        #    s
    Interface             : Optional [str] = None        #    s
    IpInterface           : Optional [str] = None        #    s
    Driver                : Optional [str] = None        #    s
    DriverVersion         : Optional [str] = None        #    s
    FirmwareVersion       : Optional [str] = None        #    s
    Capabilities          : Optional [int] = None        #    u
    Ip4Address            : Optional [int] = None        #    u
    State                 : Optional [int] = None        #    u
    StateReason           : Optional [int] = None        #    (uu)
    ActiveConnection      : Optional [str] = None        #    o
    Ip4Config             : Optional [str] = None        #    o
    Dhcp4Config           : Optional [str] = None        #    o
    Ip6Config             : Optional [str] = None        #    o
    Dhcp6Config           : Optional [str] = None        #    o
    Managed               : Optional [bool] = None       #    b
    Autoconnect           : Optional [bool] = None       #    b
    FirmwareMissing       : Optional [bool] = None       #    b
    NmPluginMissing       : Optional [bool] = None       #    b
    DeviceType            : Optional [int] = None        #    u
    AvailableConnections  : Optional [list[str]] = None  #    ao
    PhysicalPortId        : Optional [str] = None        #    s
    Mtu                   : Optional [int] = None        #    u
    Metered               : Optional [int] = None        #    u
    LldpNeighbors         : Optional [list[str]] = None  #    aa{sv}
    Real                  : Optional [bool] = None       #    b
    Ip4Connectivity       : Optional [int] = None        #    u
    Ip6Connectivity       : Optional [int] = None        #    u
    InterfaceFlags        : Optional [int] = None        #    u
    HwAddress             : Optional [str] = None        #    s
    Ports                 : Optional [list[str]] = None  #    ao
    

    @classmethod
    def from_dict(cls, data: dict[str, tuple[str, Any]]) -> Self:
        """Convert from dict of {'Prop': ('s', value)} or similar into structured props."""
        filtered = {}
        for f in fields(cls):
            if f.name in data:
                prop_data = data[f.name]
                if isinstance(prop_data, tuple) and len(prop_data) == 2:
                    filtered[f.name] = prop_data[1]
                else:
                    print("from dict ERROR")
                    filtered[f.name] = prop_data
        return cls(**filtered)


class Device(MessageGenerator):

    interface = 'org.freedesktop.NetworkManager.Device'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/Devices/2',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)

    def Reapply(self, connection, version_id, flags):
        return new_method_call(self, 'Reapply', 'a{sa{sv}}tu',
                               (connection, version_id, flags))

    def GetAppliedConnection(self, flags):
        return new_method_call(self, 'GetAppliedConnection', 'u',
                               (flags,))

    def Disconnect(self):
        return new_method_call(self, 'Disconnect')

    def Delete(self):
        return new_method_call(self, 'Delete')
    

    


    

class Wired(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Device.Wired'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/Devices/2',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)


