"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager/AgentManager
Bus name   : org.freedesktop.NetworkManager
"""

from jeepney.wrappers import MessageGenerator, new_method_call


class AgentManager(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.AgentManager'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/AgentManager',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)

    def Register(self, identifier):
        return new_method_call(self, 'Register', 's',
                               (identifier,))

    def RegisterWithCapabilities(self, identifier, capabilities):
        return new_method_call(self, 'RegisterWithCapabilities', 'su',
                               (identifier, capabilities))

    def Unregister(self):
        return new_method_call(self, 'Unregister')
