"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager/Settings/1
Bus name   : org.freedesktop.NetworkManager
"""

from dataclasses import dataclass, fields
from typing import Optional
from jeepney.wrappers import MessageGenerator, new_method_call, DBusAddress

@dataclass
class ConnectionProperties:
    def __init__(self, data):
        for f in fields(self):
            if f.name in data:
                prop_data = data[f.name]
                if isinstance(prop_data, tuple) and len(prop_data) == 2:
                    setattr(self, f.name, prop_data[1])
                else:
                    setattr(self, f.name, prop_data)
    
    Unsaved     : Optional [bool] = None        #    b
    Flags       : Optional [int] = None         #    u
    Filename    : Optional [str] = None         #    s



class Connection(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Settings.Connection'

    def __init__(self, object_path,
                 bus_name='org.freedesktop.NetworkManager'):
        
        self.props_if = DBusAddress(object_path, bus_name=bus_name, interface='org.freedesktop.DBus.Properties')
        
        super().__init__(object_path=object_path, bus_name=bus_name)

    def Update(self, properties):
        return new_method_call(self, 'Update', 'a{sa{sv}}',
                               (properties,))

    def UpdateUnsaved(self, properties):
        return new_method_call(self, 'UpdateUnsaved', 'a{sa{sv}}',
                               (properties,))

    def Delete(self):
        return new_method_call(self, 'Delete')

    def GetSettings(self):
        return new_method_call(self, 'GetSettings')

    def GetSecrets(self, setting_name):
        return new_method_call(self, 'GetSecrets', 's',
                               (setting_name,))

    def ClearSecrets(self):
        return new_method_call(self, 'ClearSecrets')

    def Save(self):
        return new_method_call(self, 'Save')

    def Update2(self, settings, flags, args):
        return new_method_call(self, 'Update2', 'a{sa{sv}}ua{sv}',
                               (settings, flags, args))
        
######################################################################
    
    def get(self, name):
        """Get the value of the property *name*"""
        return new_method_call(self.props_if, 'Get', 'ss',
                   (self.interface, name))

    def get_all(self):
        """Get all property values for this interface"""
        return new_method_call(self.props_if, 'GetAll', 's',
                               (self.interface,))


    def set(self, name, signature, value):
        """Set the property *name* to *value* (with appropriate signature)"""
        return new_method_call(self.props_if, 'Set', 'ssv',
                   (self.interface, name, (signature, value)))