"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager
Bus name   : org.freedesktop.NetworkManager
"""

from typing import Any, Optional
from jeepney.wrappers import MessageGenerator, new_method_call, DBusAddress
from dataclasses import dataclass, fields

@dataclass
class NetworkManagerProperties:
    def __init__(self, data):
        for f in fields(self):
            if f.name in data:
                prop_data = data[f.name]
                if isinstance(prop_data, tuple) and len(prop_data) == 2:
                    setattr(self, f.name, prop_data[1])
                else:
                    setattr(self, f.name, prop_data)
    Devices                     : Optional [list[str]] = None #readable   ao
    AllDevices                  : Optional [list[str]] = None #readable   ao
    Checkpoints                 : Optional [list[str]] = None #readable   ao
    NetworkingEnabled           : Optional [bool] = None #readable   b
    WirelessEnabled             : Optional [bool] = None #readwrite  b
    WirelessHardwareEnabled     : Optional [bool] = None #readable   b
    WwanEnabled                 : Optional [bool] = None #readwrite  b
    WwanHardwareEnabled         : Optional [bool] = None #readable   b
    WimaxEnabled                : Optional [bool] = None #readwrite  b
    WimaxHardwareEnabled        : Optional [bool] = None #readable   b
    RadioFlags                  : Optional [int] = None #readable   u
    ActiveConnections           : Optional [list[str]] = None #readable   ao
    PrimaryConnection           : Optional [str] = None #readable   o
    PrimaryConnectionType       : Optional [str] = None #readable   s
    Metered                     : Optional [int] = None #readable   u
    ActivatingConnection        : Optional [str] = None #readable   o
    Startup                     : Optional [bool] = None #readable   b
    Version                     : Optional [str] = None #readable   s
    VersionInfo                 : Optional [list[int]] = None #readable   au
    Capabilities                : Optional [list[int]] = None #readable   au
    State                       : Optional [int] = None #readable   u
    Connectivity                : Optional [int] = None #readable   u
    ConnectivityCheckAvailable  : Optional [bool] = None #readable   b
    ConnectivityCheckEnabled    : Optional [bool] = None #readwrite  b
    ConnectivityCheckUri        : Optional [str] = None #readable   s
    GlobalDnsConfiguration      : Optional [dict[str, Any]] = None #readwrite  a{sv}


class NetworkManager(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager'

    def __init__(self, object_path='/org/freedesktop/NetworkManager',
                 bus_name='org.freedesktop.NetworkManager'):
    
        self.props_if = DBusAddress(object_path, bus_name=bus_name, interface='org.freedesktop.DBus.Properties')    
    
        super().__init__(object_path=object_path, bus_name=bus_name)

    def Reload(self, flags):
        return new_method_call(self, 'Reload', 'u',
                               (flags,))

    def GetDevices(self):
        return new_method_call(self, 'GetDevices')

    def GetAllDevices(self):
        return new_method_call(self, 'GetAllDevices')

    def GetDeviceByIpIface(self, iface):
        return new_method_call(self, 'GetDeviceByIpIface', 's',
                               (iface,))

    def ActivateConnection(self, connection, device, specific_object):
        return new_method_call(self, 'ActivateConnection', 'ooo',
                               (connection, device, specific_object))

    def AddAndActivateConnection(self, connection, device, specific_object):
        return new_method_call(self, 'AddAndActivateConnection', 'a{sa{sv}}oo',
                               (connection, device, specific_object))

    def AddAndActivateConnection2(self, connection, device, specific_object, options):
        return new_method_call(self, 'AddAndActivateConnection2', 'a{sa{sv}}ooa{sv}',
                               (connection, device, specific_object, options))

    def DeactivateConnection(self, active_connection):
        return new_method_call(self, 'DeactivateConnection', 'o',
                               (active_connection,))

    def Sleep(self, sleep):
        return new_method_call(self, 'Sleep', 'b',
                               (sleep,))

    def Enable(self, enable):
        return new_method_call(self, 'Enable', 'b',
                               (enable,))

    def GetPermissions(self):
        return new_method_call(self, 'GetPermissions')

    def SetLogging(self, level, domains):
        return new_method_call(self, 'SetLogging', 'ss',
                               (level, domains))

    def GetLogging(self):
        return new_method_call(self, 'GetLogging')

    def CheckConnectivity(self):
        return new_method_call(self, 'CheckConnectivity')

    def state(self):
        return new_method_call(self, 'state')

    def CheckpointCreate(self, devices, rollback_timeout, flags):
        return new_method_call(self, 'CheckpointCreate', 'aouu',
                               (devices, rollback_timeout, flags))

    def CheckpointDestroy(self, checkpoint):
        return new_method_call(self, 'CheckpointDestroy', 'o',
                               (checkpoint,))

    def CheckpointRollback(self, checkpoint):
        return new_method_call(self, 'CheckpointRollback', 'o',
                               (checkpoint,))

    def CheckpointAdjustRollbackTimeout(self, checkpoint, add_timeout):
        return new_method_call(self, 'CheckpointAdjustRollbackTimeout', 'ou',
                               (checkpoint, add_timeout))
        
######################################################################
    
    def get(self, name):
        """Get the value of the property *name*"""
        return new_method_call(self.props_if, 'Get', 'ss',
                   (self.interface, name))

    def get_all(self):
        """Get all property values for this interface"""
        return new_method_call(self.props_if, 'GetAll', 's',
                               (self.interface,))


    def set(self, name, signature, value):
        """Set the property *name* to *value* (with appropriate signature)"""
        return new_method_call(self.props_if, 'Set', 'ssv',
                   (self.interface, name, (signature, value)))