"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager/IP6Config/2
Bus name   : org.freedesktop.NetworkManager
"""

from jeepney.wrappers import MessageGenerator, new_method_call


class IP6Config(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.IP6Config'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/IP6Config/2',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)
