"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager/Devices/2
Bus name   : org.freedesktop.NetworkManager
"""


from dataclasses import dataclass, fields
from typing import Any, Optional
from jeepney.wrappers import MessageGenerator, new_method_call

from jeepney.wrappers import DBusAddress


class Statistics(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Device.Statistics'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/Devices/2',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)

@dataclass
class DeviceProperties:
    Udi                   : Optional [str] = None        #    s
    Path                  : Optional [str] = None        #    s
    Interface             : Optional [str] = None        #    s
    IpInterface           : Optional [str] = None        #    s
    Driver                : Optional [str] = None        #    s
    DriverVersion         : Optional [str] = None        #    s
    FirmwareVersion       : Optional [str] = None        #    s
    Capabilities          : Optional [int] = None        #    u
    Ip4Address            : Optional [int] = None        #    u
    State                 : Optional [int] = None        #    u
    StateReason           : Optional [int] = None        #    (uu)
    ActiveConnection      : Optional [str] = None        #    o
    Ip4Config             : Optional [str] = None        #    o
    Dhcp4Config           : Optional [str] = None        #    o
    Ip6Config             : Optional [str] = None        #    o
    Dhcp6Config           : Optional [str] = None        #    o
    Managed               : Optional [bool] = None       #    b
    Autoconnect           : Optional [bool] = None       #    b
    FirmwareMissing       : Optional [bool] = None       #    b
    NmPluginMissing       : Optional [bool] = None       #    b
    DeviceType            : Optional [int] = None        #    u
    AvailableConnections  : Optional [list[str]] = None  #    ao
    PhysicalPortId        : Optional [str] = None        #    s
    Mtu                   : Optional [int] = None        #    u
    Metered               : Optional [int] = None        #    u
    LldpNeighbors         : Optional [list[str]] = None  #    aa{sv}
    Real                  : Optional [bool] = None       #    b
    Ip4Connectivity       : Optional [int] = None        #    u
    Ip6Connectivity       : Optional [int] = None        #    u
    InterfaceFlags        : Optional [int] = None        #    u
    HwAddress             : Optional [str] = None        #    s
    Ports                 : Optional [list[str]] = None  #    ao

    def load(self,  data):
        '''Get all property values and store in instance. Note the 0th index'''
        for f in fields(self):
            if f.name in data:
                prop_data = data[f.name]
                if isinstance(prop_data, tuple) and len(prop_data) == 2:
                    setattr(self, f.name, prop_data[1])
                else:
                    setattr(self, f.name, prop_data)

class Device(MessageGenerator):
    
    interface = 'org.freedesktop.NetworkManager.Device'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/Devices/2',
                 bus_name='org.freedesktop.NetworkManager'):
        
        self.props_if = DBusAddress(object_path, bus_name=bus_name, interface='org.freedesktop.DBus.Properties')

        self.props = DeviceProperties()

        super().__init__(object_path=object_path, bus_name=bus_name)


    def Reapply(self, connection, version_id, flags):
        return new_method_call(self, 'Reapply', 'a{sa{sv}}tu',
                               (connection, version_id, flags))

    def GetAppliedConnection(self, flags):
        return new_method_call(self, 'GetAppliedConnection', 'u',
                               (flags,))

    def Disconnect(self):
        return new_method_call(self, 'Disconnect')

    def Delete(self):
        return new_method_call(self, 'Delete')
    
######################################################################
    
    def get(self, name):
        """Get the value of the property *name*"""
        return new_method_call(self.props_if, 'Get', 'ss',
                   (self.interface, name))

    def get_all(self):
        """Get all property values for this interface"""
        return new_method_call(self.props_if, 'GetAll', 's',
                               (self.interface,))


    def set(self, name, signature, value):
        """Set the property *name* to *value* (with appropriate signature)"""
        return new_method_call(self.props_if, 'Set', 'ssv',
                   (self.interface, name, (signature, value)))
    
    

    

class Wired(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Device.Wired'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/Devices/2',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)


