"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager/Settings
Bus name   : org.freedesktop.NetworkManager
"""

from jeepney.wrappers import MessageGenerator, new_method_call


class Settings(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Settings'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/Settings',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)

    def ListConnections(self):
        return new_method_call(self, 'ListConnections')

    def GetConnectionByUuid(self, uuid):
        return new_method_call(self, 'GetConnectionByUuid', 's',
                               (uuid,))

    def AddConnection(self, connection):
        return new_method_call(self, 'AddConnection', 'a{sa{sv}}',
                               (connection,))

    def AddConnectionUnsaved(self, connection):
        return new_method_call(self, 'AddConnectionUnsaved', 'a{sa{sv}}',
                               (connection,))

    def AddConnection2(self, settings, flags, args):
        return new_method_call(self, 'AddConnection2', 'a{sa{sv}}ua{sv}',
                               (settings, flags, args))

    def LoadConnections(self, filenames):
        return new_method_call(self, 'LoadConnections', 'as',
                               (filenames,))

    def ReloadConnections(self):
        return new_method_call(self, 'ReloadConnections')

    def SaveHostname(self, hostname):
        return new_method_call(self, 'SaveHostname', 's',
                               (hostname,))
