"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager/ActiveConnection/4
Bus name   : org.freedesktop.NetworkManager
"""

from jeepney.wrappers import MessageGenerator, new_method_call


class ActiveConnection(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Connection.Active'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/ActiveConnection/4',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)
