"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager/ActiveConnection/4
Bus name   : org.freedesktop.NetworkManager
"""

from dataclasses import dataclass, fields
from typing import Any, Optional
from jeepney.wrappers import MessageGenerator, new_method_call, DBusAddress


@dataclass
class ActiveConnectionProperties:
    def __init__(self, data):
        for f in fields(self):
            if f.name in data:
                prop_data = data[f.name]
                if isinstance(prop_data, tuple) and len(prop_data) == 2:
                    setattr(self, f.name, prop_data[1])
                else:
                    setattr(self, f.name, prop_data)
                    
    Connection      :Optional [str] = None        #   o
    SpecificObject  :Optional [str] = None        #   o
    Id              :Optional [str] = None        #   s
    Uuid            :Optional [str] = None        #   s
    Type            :Optional [str] = None        #   s
    Devices         :Optional [list[str]] = None  #   ao
    State           :Optional [int] = None        #   u
    StateFlags      :Optional [int] = None        #   u
    Default         :Optional [bool] = None       #   b
    Ip4Config       :Optional [str] = None        #   o
    Dhcp4Config     :Optional [str] = None        #   o
    Default6        :Optional [str] = None        #   b
    Ip6Config       :Optional [str] = None        #   o
    Dhcp6Config     :Optional [str] = None        #   o
    Vpn             :Optional [bool] = None       #   b
    Controller      :Optional [str] = None        #   o
    Master          :Optional [str] = None        #   o


class ActiveConnection(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Connection.Active'

    def __init__(self, object_path,
                 bus_name='org.freedesktop.NetworkManager'):
        
        self.props_if = DBusAddress(object_path, bus_name=bus_name, interface='org.freedesktop.DBus.Properties')
        
        super().__init__(object_path=object_path, bus_name=bus_name)
        
######################################################################
    
    def get(self, name):
        """Get the value of the property *name*"""
        return new_method_call(self.props_if, 'Get', 'ss',
                   (self.interface, name))

    def get_all(self):
        """Get all property values for this interface"""
        return new_method_call(self.props_if, 'GetAll', 's',
                               (self.interface,))


    def set(self, name, signature, value):
        """Set the property *name* to *value* (with appropriate signature)"""
        return new_method_call(self.props_if, 'Set', 'ssv',
                   (self.interface, name, (signature, value)))

