"""Auto-generated DBus bindings

Generated by jeepney version 0.8.0

Object path: /org/freedesktop/NetworkManager/Devices/2
Bus name   : org.freedesktop.NetworkManager
"""

from jeepney.wrappers import MessageGenerator, new_method_call


class Statistics(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Device.Statistics'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/Devices/2',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)

class Device(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Device'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/Devices/2',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)

    def Reapply(self, connection, version_id, flags):
        return new_method_call(self, 'Reapply', 'a{sa{sv}}tu',
                               (connection, version_id, flags))

    def GetAppliedConnection(self, flags):
        return new_method_call(self, 'GetAppliedConnection', 'u',
                               (flags,))

    def Disconnect(self):
        return new_method_call(self, 'Disconnect')

    def Delete(self):
        return new_method_call(self, 'Delete')

class Wired(MessageGenerator):
    interface = 'org.freedesktop.NetworkManager.Device.Wired'

    def __init__(self, object_path='/org/freedesktop/NetworkManager/Devices/2',
                 bus_name='org.freedesktop.NetworkManager'):
        super().__init__(object_path=object_path, bus_name=bus_name)
